name: Publish container image

# ${{ github.ref_name }} is set to the branch name, and is used to build &
# tag the container image
#
on:
  workflow_dispatch:  # execute on manual execution
  push:               # execute on pushes to development or master branches
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.ref_name }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      IMAGE_NAME: infinite-industries/discord-bot
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
      - name: install casey/just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.13.0
      - name: build the image
        run: just build-image
      - name: publish the image
        run: just registry_user=${{ github.actor }} publish
